#!/usr/bin/awk -f

/Generated by wayland-scanner/ {
    print $0
    print "/* webOS ABI fix patch applied */"
    next
}

/webOS ABI fix patch applied/ {
    print "ERROR: webOS ABI fix patch already applied" > "/dev/stderr"
    exit 1
}

/^#include "wayland-client.h"/ {
    print $0
    print "#include \"wayland-webos-abifix.h\""
    next
}

/^#define WL_WEBOS_INPUT_MANAGER_/ {
    if ($0 ~ /_SINCE_VERSION/) {
        print $0
    } else {
        printf("%s %s wl_webos_input_manager_abifix.methods[%s].opcode\n", $1, $2, $3)
    }
    next
}

{ print $0 }
